# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tomáš Kubica
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
   na cestě do cloudu
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tomaskubica.cz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tkubica
linkedin_username: tkubica
github_username:  tkubica12

highlighter: rouge

kramdown:
  input:          GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
permalink: /post/:year/:title/
# Build settings
markdown: kramdown
#theme: jekyll-theme-hydejack
theme: jekyll-theme-clean-blog
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll/tagging
  - jekyll-sitemap

pagination:
  enabled: true
  per_page: 5
  offset: 0
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

tag_page_layout: tag_page
tag_page_dir: tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - cicd/
  - certs/
  - notes.md
